import { StyleSheet } from 'react-native';
import Colors from './Colors';
import Fonts from './Fonts';
import { Metrics, moderateScale, scale, verticalScale } from './Metrics';

const styles = (colors) =>
  StyleSheet.create({
    mainContainer: {
      flex: 1,
      backgroundColor: colors.mainBackground,
    },
    detailContainer: {
      flex: 1,
      backgroundColor: colors.background,
    },
    loginBackground: {
      flex: 1,
      alignItems: 'center',
      backgroundColor: colors.background,
      borderTopLeftRadius: moderateScale(25),
      borderTopRightRadius: moderateScale(25),
      elevation: 75,
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowColor: colors.shadow,
      shadowOpacity: 0.05,
      shadowRadius: verticalScale(20),
    },
    loginInputContainer: {
      width: Metrics.screenWidth - scale(60),
      flexDirection: 'row',
      alignItems: 'center',
      height: verticalScale(50),
      marginTop: verticalScale(30),
      borderRadius: moderateScale(40),
      borderWidth: 1,
      borderColor: colors.inactive,
      paddingHorizontal: scale(20),
    },
    loginInputIcon: {
      marginRight: scale(20),
    },
    loginInput: {
      fontFamily: Fonts.type.nunitoSans.regular,
      fontSize: Fonts.size.label,
      color: colors.textPrimary,
      padding: 0,
    },
    loginButton: {
      width: Metrics.screenWidth - scale(60),
      height: verticalScale(50),
      marginTop: verticalScale(40),
      borderRadius: moderateScale(40),
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primary,
    },
    loginButtonText: {
      fontFamily: Fonts.type.nunitoSans.bold,
      fontSize: Fonts.size.input,
      color: Colors.white,
    },
    tabTitle: {
      fontFamily: Fonts.type.nunitoSans.regular,
      fontSize: Fonts.size.small,
      color: colors.primary,
      marginTop: verticalScale(10),
    },
    tabTitleInactive: {
      color: colors.inactive,
    },
    tabProfile: {
      padding: moderateScale(8),
      borderRadius: moderateScale(20),
      backgroundColor: colors.primaryOpacity10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerContainer: {
      marginTop: verticalScale(10),
      marginHorizontal: scale(24),
      flexDirection: 'row',
      alignItems: 'center',
    },
    headerRightContainer: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    headerProfileImageContainer: {
      width: moderateScale(48),
      height: moderateScale(48),
      borderRadius: moderateScale(6),
      backgroundColor: colors.primaryOpacity10,
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
    },
    headerProfileImage: {
      width: '100%',
      height: '100%',
    },
    headerIconMarginStyle: {
      marginRight: scale(20),
    },
    headerTitle: {
      flex: 1,
      fontFamily: Fonts.type.nunitoSans.bold,
      fontSize: Fonts.size.h5,
      color: colors.inactive2,
      paddingHorizontal: scale(10),
    },
    createGameTitleText: {
      fontFamily: Fonts.type.lato.bold,
      fontSize: Fonts.size.label,
      color: colors.inactive2Opacity60,
      marginTop: verticalScale(24),
      marginHorizontal: scale(24),
    },
    buttonContainer: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      marginBottom: verticalScale(24),
      marginHorizontal: scale(12),
      flexDirection: 'row',
      alignItems: 'center',
    },
    primaryButtonStyle: {
      flex: 1,
      marginHorizontal: scale(12),
      height: verticalScale(50),
      borderRadius: moderateScale(10),
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primary,
    },
    primaryButtonText: {
      fontFamily: Fonts.type.lato.bold,
      fontSize: Fonts.size.medium,
      color: Colors.white,
    },
    primaryButtonInactiveStyle: {
      flex: 1,
      marginHorizontal: scale(12),
      height: verticalScale(50),
      borderRadius: moderateScale(10),
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.buttonInactive,
    },
    primaryButtonInactiveText: {
      fontFamily: Fonts.type.lato.bold,
      fontSize: Fonts.size.medium,
      color: colors.inactive,
    },
    secondaryButtonStyle: {
      flex: 1,
      marginHorizontal: scale(12),
      height: verticalScale(50),
      borderRadius: moderateScale(10),
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: moderateScale(1),
      borderColor: colors.primary,
      backgroundColor: colors.background,
    },
    secondaryButtonText: {
      fontFamily: Fonts.type.lato.bold,
      fontSize: Fonts.size.medium,
      color: colors.primary,
    },
    inputView: {
      marginHorizontal: scale(24),
      marginTop: verticalScale(12),
      paddingVertical: verticalScale(16),
      borderRadius: moderateScale(10),
      backgroundColor: colors.inactive3,
    },
    inputViewText: {
      fontFamily: Fonts.type.lato.regular,
      fontSize: Fonts.size.medium,
      color: colors.inactive2,
    },
    inputViewInactiveText: {
      fontFamily: Fonts.type.lato.regular,
      fontSize: Fonts.size.medium,
      color: colors.inactive,
    },
    datePickerDateTextStyle: {
      fontFamily: Fonts.type.lato.regular,
      fontSize: Fonts.size.medium,
      color: colors.inactive,
    },
    datePickerDatePlaceholderTextStyle: {
      fontFamily: Fonts.type.lato.regular,
      fontSize: Fonts.size.medium,
      color: colors.inactive2,
    },
    datePickerBtnTextStyle: {
      fontFamily: Fonts.type.lato.regular,
      fontSize: Fonts.size.label,
      color: colors.textInactive,
    },
    priceTextStyle: {
      fontFamily: Fonts.type.lato.regular,
      fontSize: Fonts.size.medium,
      color: colors.textInactive,
    },
    priceInputContainer: {
      width: scale(80),
      height: verticalScale(55),
      flexDirection: 'row',
      alignItems: 'center',
      borderRadius: moderateScale(10),
      borderWidth: moderateScale(1),
      borderColor: colors.inactive,
      paddingHorizontal: scale(20),
    },
    priceInput: {
      flex: 1,
      fontFamily: Fonts.type.lato.regular,
      fontSize: Fonts.size.medium,
      color: colors.textInactive,
      padding: 0,
    },
    mainHeaderTitle: {
      fontFamily: Fonts.type.nunitoSans.bold,
      fontSize: Fonts.size.h5,
      color: colors.textPrimary,
    },
    listHeaderContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: verticalScale(25),
      marginLeft: scale(24),
    },
    listHeaderTitle: {
      fontFamily: Fonts.type.nunitoSans.bold,
      fontSize: Fonts.size.input,
      color: colors.textPrimary,
      marginLeft: scale(28),
    },
    listHeaderSubTitle: {
      fontFamily: Fonts.type.nunitoSans.bold,
      fontSize: Fonts.size.input,
      color: colors.textPrimaryOpacity40,
      marginLeft: scale(15),
    },
    dashItemContainer: {
      marginTop: verticalScale(20),
      padding: moderateScale(20),
      borderRadius: moderateScale(25),
      marginHorizontal: scale(20),
      backgroundColor: colors.background,
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowColor: colors.shadow,
      shadowOpacity: 0.1,
      shadowRadius: moderateScale(10),
      elevation: 5,
    },
    dashItemInnerContainer: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    dashItemImageContainer: {
      width: moderateScale(85),
      height: moderateScale(85),
      borderRadius: moderateScale(17),
      backgroundColor: colors.primaryOpacity10,
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
    },
    dashItemImage: {
      width: '100%',
      height: '100%',
    },
    dashItemContentContainer: {
      flex: 1,
      marginLeft: scale(20),
    },
    dashItemContextTextContainer: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    dashItemContentText: {
      fontFamily: Fonts.type.nunitoSans.bold,
      fontSize: Fonts.size.h5,
      color: colors.textPrimary,
    },
    dashItemRoundSmallContainer: {
      paddingVertical: verticalScale(8),
      paddingHorizontal: scale(10),
      borderRadius: moderateScale(25),
      backgroundColor: colors.primaryOpacity10,
      marginLeft: scale(10),
    },
    dashItemRoundContainer: {
      paddingVertical: verticalScale(8),
      paddingHorizontal: scale(16),
      borderRadius: moderateScale(30),
      backgroundColor: colors.primaryOpacity10,
      marginTop: verticalScale(13),
      alignSelf: 'flex-start',
    },
    dashItemRoundText: {
      fontFamily: Fonts.type.nunitoSans.bold,
      fontSize: Fonts.size.input,
      color: colors.primary,
    },
    dashItemTimeText: {
      fontFamily: Fonts.type.nunitoSans.regular,
      fontSize: Fonts.size.medium,
      color: colors.inactive2Opacity80,
      marginTop: verticalScale(5),
    },
    dashItemUserListMainContainer: {
      marginTop: verticalScale(15),
    },
    dashItemUserListContainer: {
      width: moderateScale(28),
      height: moderateScale(28),
      borderRadius: moderateScale(14),
      borderWidth: moderateScale(2),
      borderColor: colors.background,
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
    },
    dashItemUserListMoreContainer: {
      backgroundColor: colors.primary,
    },
    dashItemUserMoreText: {
      fontFamily: Fonts.type.nunitoSans.semiBold,
      fontSize: Fonts.size.small,
      color: Colors.white,
    },
    dashItemUserListMargin: {
      marginLeft: -moderateScale(8),
    },
    dashItemButtonContainer: {
      paddingVertical: verticalScale(16),
      backgroundColor: colors.primary,
      borderRadius: moderateScale(30),
      marginTop: verticalScale(20),
      alignItems: 'center',
    },
    dashItemButtonText: {
      fontFamily: Fonts.type.nunitoSans.bold,
      fontSize: Fonts.size.input,
      color: Colors.white,
    },
    dashItemFooterContainer: {
      height: verticalScale(30),
    },
    joinTeamTitle: {
      fontFamily: Fonts.type.lato.bold,
      fontSize: Fonts.size.h3,
      color: colors.textPrimary,
    },
    joinTeamOverallContainer: {
      width: scale(70),
      height: verticalScale(40),
      borderRadius: moderateScale(10),
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primary,
      marginTop: verticalScale(15),
    },
    joinTeamOverallText: {
      fontFamily: Fonts.type.lato.bold,
      fontSize: Fonts.size.input,
      color: Colors.white,
    },
    joinTeamVSText: {
      fontFamily: Fonts.type.lato.bold,
      fontSize: Fonts.size.h5,
      color: colors.textPrimary,
    },
    joinBorder: {
      height: moderateScale(2),
      backgroundColor: colors.border,
    },
    joinItemContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: verticalScale(24),
    },
    joinItemImageContainer: {
      width: moderateScale(50),
      height: moderateScale(50),
      borderRadius: moderateScale(25),
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.inactive3,
      overflow: 'hidden',
    },
    joinItemOverallContainer: {
      width: moderateScale(26),
      height: moderateScale(26),
      borderRadius: moderateScale(13),
      alignItems: 'center',
      justifyContent: 'center',
      position: 'absolute',
      right: -moderateScale(7),
      top: -moderateScale(7),
      backgroundColor: colors.primaryLight,
    },
    joinItemOverallText: {
      fontFamily: Fonts.type.lato.regular,
      fontSize: Fonts.size.small,
      color: Colors.white,
    },
    joinItemTextContainer: {
      flex: 1,
      marginLeft: scale(12),
    },
    joinItemName: {
      fontFamily: Fonts.type.lato.bold,
      fontSize: Fonts.size.input,
      color: colors.textPrimary,
    },
    joinItemRole: {
      fontFamily: Fonts.type.lato.regular,
      fontSize: Fonts.size.medium,
      color: colors.textInactive,
      marginTop: verticalScale(1),
    },
    iconButtonStyle: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: scale(24),
      paddingVertical: verticalScale(16),
      borderRadius: moderateScale(30),
      backgroundColor: colors.primary,
    },
    iconButtonText: {
      fontFamily: Fonts.type.lato.bold,
      fontSize: Fonts.size.input,
      color: Colors.white,
    },
    rateItemChamContainer: {
      width: moderateScale(50),
      height: moderateScale(50),
      borderRadius: moderateScale(25),
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: moderateScale(2),
      borderColor: colors.inactive,
    },
    rateItemChamContainerActive: {
      borderWidth: 0,
      borderColor: Colors.transparent,
      backgroundColor: colors.primary,
    },
    rateItemRatingContainer: {
      alignSelf: 'flex-start',
      marginTop: verticalScale(5),
    },
    chatLeftBubble: {
      backgroundColor: colors.inactive2,
    },
    chatRightBubble: {
      backgroundColor: colors.primary,
    },
    chatLeftTextStyle: {
      fontFamily: Fonts.type.lato.regular,
      fontSize: Fonts.size.label,
      color: colors.inactive,
    },
    chatRightTextStyle: {
      fontFamily: Fonts.type.lato.regular,
      fontSize: Fonts.size.label,
      color: Colors.white,
    },
    chatTimeTextStyle: {
      fontFamily: Fonts.type.lato.regular,
      fontSize: Fonts.size.medium,
      color: colors.inactive2,
    },
    chatSendMessageInput: {
      fontFamily: Fonts.type.lato.regular,
      fontSize: Fonts.size.input,
      color: colors.textPrimary,
    },
    chatSendMessageText: {
      fontFamily: Fonts.type.lato.regular,
      fontSize: Fonts.size.regular,
      color: colors.textInactive,
    },
  });

export default styles;
