const Strings = {
  appName: 'ImInn',
  welcome: 'Welcome back to IMINN!',
  loginMessage: 'Let’s Login into your Account!',
  login: 'Login',
  signUp: 'Sign Up',
  emailPlaceholder: 'E-Mail Address',
  password: 'Password',
  orUsing: 'OR USING',
  google: 'Google',
  facebook: 'Facebook',
  selectRoleMessage: 'Select a Role that’s Fit with you!',
  keeper: 'Keeper',
  defender: 'Defender',
  midfielder: 'Midfielder',
  striker: 'Striker',
  select: 'Select',
  emptyMatches: 'There are no matches in your area',
  information: 'Information',
  details: 'Details',
  publish: 'Publish',
  games: 'Games',
  rokie: 'Rokie',
  yourGames: 'Your Games',
  moreDetails: 'More Details',
  recommendation: 'Recommendation',
  nearby: 'Nearby',
  joinNow: 'Join Now',
  createGame: 'Create Game',
  youAre: 'You Are',
  organizer: 'Organizer',
  player: 'Player',
  typePitch: 'Type Pitch',
  teamName: 'Team Name',
  vs: 'VS',
  continue: 'Continue',
  previous: 'Previous',
  publishNow: 'Publish Now',
  setLocation: 'Set Location',
  setDate: 'Set Date',
  setTime: 'Set Time',
  setPrice: 'Set Price',
  am: 'AM',
  pm: 'PM',
  confirm: 'Confirm',
  cancel: 'Cancel',
  perPerson: '/ Person',
  playerPerTeam: 'Players / Team',
  setGameAs: 'Set Game As',
  public: 'Public',
  private: 'Private',
  publicContent:
    'It’s mean that anyone can join the game and see the game in the list of games, so it’s publicly published',
  privateContent:
    'It’s mean that only people that has a generated code given can join the game.',
  teamA: 'Team A',
  teamB: 'Team B',
  joined: 'Joined',
  joinGame: 'Join Game',
  join: 'Join',
  unJoin: 'Un-Join',
  chat: 'Chat',
  ratePlayer: 'Rate Player',
};

export default Strings;
